"""
This module defines the parsers for the synonym file.
"""

from abc import ABC, abstractmethod


class AbstractSynonymParser(ABC):

    """
    An abstract base class for which defines a synonym file parser.
    """

    @abstractmethod
    def __init__(self, synonym_file):
        """
        In a subclass method should instantiate the parser and use the
        parse method (see below) to read the file and generate the
        synonyms_dict class variable
        """
        pass

    @abstractmethod
    def parse(self, file_name):
        """
        In a subclass this method should read the file given as the
        argument file_name and generates a dict of synonyms.
        """
        pass

    @abstractmethod
    def get_synonyms(self):
        """
        In a subclass this method should return the synonyms
        dictionary generated by the parser.

        @return a dictionary of strings which maps a synonym to the
        first synonym in the list of synonyms as defined in the synonym file
        """
        pass


class SpaceSeparatedSynonymFileParser(AbstractSynonymParser):

    """
    A class which instantiates a parser for the space separated
    synonym file format.
    """

    def __init__(self, synonym_file):
        self.synonym_dict = {}
        self.parse(synonym_file)

    def parse(self, file_name):
        """
        Reads the file given as the argument file_name and generates a
        dict of synonyms.
        @return None
        """
        with open(file_name) as file_handler:
            for line in file_handler.readlines():
                words = line.split()
                synonym = words[0].lower()
                for word in words:
                    self.synonym_dict[word.lower()] = synonym
        return

    def get_synonyms(self):
        """
        This method returns the list of synonyms dict generated by the parser.

        @return a dictionary of strings which maps a synonym to the
        first synonym in the list of synonyms as defined in the synonym file
        """
        return self.synonym_dict
